INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CORRELATE_AND_DELAY correlate_and_delay)

FIND_PATH(
    CORRELATE_AND_DELAY_INCLUDE_DIRS
    NAMES correlate_and_delay/api.h
    HINTS $ENV{CORRELATE_AND_DELAY_DIR}/include
        ${PC_CORRELATE_AND_DELAY_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CORRELATE_AND_DELAY_LIBRARIES
    NAMES gnuradio-correlate_and_delay
    HINTS $ENV{CORRELATE_AND_DELAY_DIR}/lib
        ${PC_CORRELATE_AND_DELAY_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CORRELATE_AND_DELAY DEFAULT_MSG CORRELATE_AND_DELAY_LIBRARIES CORRELATE_AND_DELAY_INCLUDE_DIRS)
MARK_AS_ADVANCED(CORRELATE_AND_DELAY_LIBRARIES CORRELATE_AND_DELAY_INCLUDE_DIRS)

