INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_TESTING_SINGLE_SCRAMBLE testing_single_scramble)

FIND_PATH(
    TESTING_SINGLE_SCRAMBLE_INCLUDE_DIRS
    NAMES testing_single_scramble/api.h
    HINTS $ENV{TESTING_SINGLE_SCRAMBLE_DIR}/include
        ${PC_TESTING_SINGLE_SCRAMBLE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    TESTING_SINGLE_SCRAMBLE_LIBRARIES
    NAMES gnuradio-testing_single_scramble
    HINTS $ENV{TESTING_SINGLE_SCRAMBLE_DIR}/lib
        ${PC_TESTING_SINGLE_SCRAMBLE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TESTING_SINGLE_SCRAMBLE DEFAULT_MSG TESTING_SINGLE_SCRAMBLE_LIBRARIES TESTING_SINGLE_SCRAMBLE_INCLUDE_DIRS)
MARK_AS_ADVANCED(TESTING_SINGLE_SCRAMBLE_LIBRARIES TESTING_SINGLE_SCRAMBLE_INCLUDE_DIRS)

