# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_scrambler_packets_same_seed_swig')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_scrambler_packets_same_seed_swig')
    _scrambler_packets_same_seed_swig = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_scrambler_packets_same_seed_swig', [dirname(__file__)])
        except ImportError:
            import _scrambler_packets_same_seed_swig
            return _scrambler_packets_same_seed_swig
        try:
            _mod = imp.load_module('_scrambler_packets_same_seed_swig', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _scrambler_packets_same_seed_swig = swig_import_helper()
    del swig_import_helper
else:
    import _scrambler_packets_same_seed_swig
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
    """high_res_timer_now() -> gr::high_res_timer_type"""
    return _scrambler_packets_same_seed_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
    """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
    return _scrambler_packets_same_seed_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
    """high_res_timer_tps() -> gr::high_res_timer_type"""
    return _scrambler_packets_same_seed_swig.high_res_timer_tps()

def high_res_timer_epoch():
    """high_res_timer_epoch() -> gr::high_res_timer_type"""
    return _scrambler_packets_same_seed_swig.high_res_timer_epoch()
class scramble_packetize(object):
    """
    <+description of block+>

    Constructor Specific Documentation:

    Return a shared_ptr to a new instance of scrambler_packets_same_seed::scramble_packetize.

    To avoid accidental use of raw pointers, scrambler_packets_same_seed::scramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::scramble_packetize::make is the public interface for creating new instances.

    Args:
        mask : 
        seed : 
        len : 
        frame_bit : 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def make(mask, seed, len, frame_bit):
        """
        make(int mask, int seed, int len, int frame_bit) -> scramble_packetize_sptr

        <+description of block+>

        Constructor Specific Documentation:

        Return a shared_ptr to a new instance of scrambler_packets_same_seed::scramble_packetize.

        To avoid accidental use of raw pointers, scrambler_packets_same_seed::scramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::scramble_packetize::make is the public interface for creating new instances.

        Args:
            mask : 
            seed : 
            len : 
            frame_bit : 
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_make(mask, seed, len, frame_bit)

    make = staticmethod(make)
    __swig_destroy__ = _scrambler_packets_same_seed_swig.delete_scramble_packetize
    __del__ = lambda self: None
scramble_packetize_swigregister = _scrambler_packets_same_seed_swig.scramble_packetize_swigregister
scramble_packetize_swigregister(scramble_packetize)

def scramble_packetize_make(mask, seed, len, frame_bit):
    """
    scramble_packetize_make(int mask, int seed, int len, int frame_bit) -> scramble_packetize_sptr

    <+description of block+>

    Constructor Specific Documentation:

    Return a shared_ptr to a new instance of scrambler_packets_same_seed::scramble_packetize.

    To avoid accidental use of raw pointers, scrambler_packets_same_seed::scramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::scramble_packetize::make is the public interface for creating new instances.

    Args:
        mask : 
        seed : 
        len : 
        frame_bit : 
    """
    return _scrambler_packets_same_seed_swig.scramble_packetize_make(mask, seed, len, frame_bit)

class scramble_packetize_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::scrambler_packets_same_seed::scramble_packetize)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(gr::scrambler_packets_same_seed::scramble_packetize)> self) -> scramble_packetize_sptr
        __init__(boost::shared_ptr<(gr::scrambler_packets_same_seed::scramble_packetize)> self, scramble_packetize p) -> scramble_packetize_sptr
        """
        this = _scrambler_packets_same_seed_swig.new_scramble_packetize_sptr(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __deref__(self):
        """__deref__(scramble_packetize_sptr self) -> scramble_packetize"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr___deref__(self)

    __swig_destroy__ = _scrambler_packets_same_seed_swig.delete_scramble_packetize_sptr
    __del__ = lambda self: None

    def make(self, mask, seed, len, frame_bit):
        """
        make(scramble_packetize_sptr self, int mask, int seed, int len, int frame_bit) -> scramble_packetize_sptr

        <+description of block+>

        Constructor Specific Documentation:

        Return a shared_ptr to a new instance of scrambler_packets_same_seed::scramble_packetize.

        To avoid accidental use of raw pointers, scrambler_packets_same_seed::scramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::scramble_packetize::make is the public interface for creating new instances.

        Args:
            mask : 
            seed : 
            len : 
            frame_bit : 
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_make(self, mask, seed, len, frame_bit)


    def history(self):
        """history(scramble_packetize_sptr self) -> unsigned int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(scramble_packetize_sptr self, int which, int delay)
        declare_sample_delay(scramble_packetize_sptr self, unsigned int delay)
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(scramble_packetize_sptr self, int which) -> unsigned int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(scramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(scramble_packetize_sptr self) -> double"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_relative_rate(self)


    def start(self):
        """start(scramble_packetize_sptr self) -> bool"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_start(self)


    def stop(self):
        """stop(scramble_packetize_sptr self) -> bool"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(scramble_packetize_sptr self, unsigned int which_input) -> uint64_t"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(scramble_packetize_sptr self, unsigned int which_output) -> uint64_t"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(scramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(scramble_packetize_sptr self, int m)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(scramble_packetize_sptr self)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(scramble_packetize_sptr self) -> bool"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(scramble_packetize_sptr self, int m)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(scramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(scramble_packetize_sptr self, int i) -> long"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(scramble_packetize_sptr self, long max_output_buffer)
        set_max_output_buffer(scramble_packetize_sptr self, int port, long max_output_buffer)
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(scramble_packetize_sptr self, int i) -> long"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(scramble_packetize_sptr self, long min_output_buffer)
        set_min_output_buffer(scramble_packetize_sptr self, int port, long min_output_buffer)
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(scramble_packetize_sptr self, int which) -> float
        pc_input_buffers_full(scramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(scramble_packetize_sptr self, int which) -> float
        pc_input_buffers_full_avg(scramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(scramble_packetize_sptr self, int which) -> float
        pc_input_buffers_full_var(scramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(scramble_packetize_sptr self, int which) -> float
        pc_output_buffers_full(scramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(scramble_packetize_sptr self, int which) -> float
        pc_output_buffers_full_avg(scramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(scramble_packetize_sptr self, int which) -> float
        pc_output_buffers_full_var(scramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(scramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(scramble_packetize_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(scramble_packetize_sptr self)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(scramble_packetize_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(scramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(scramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(scramble_packetize_sptr self, int priority) -> int"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(scramble_packetize_sptr self) -> std::string"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_name(self)


    def symbol_name(self):
        """symbol_name(scramble_packetize_sptr self) -> std::string"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(scramble_packetize_sptr self) -> io_signature_sptr"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(scramble_packetize_sptr self) -> io_signature_sptr"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(scramble_packetize_sptr self) -> long"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(scramble_packetize_sptr self) -> basic_block_sptr"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(scramble_packetize_sptr self, int ninputs, int noutputs) -> bool"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(scramble_packetize_sptr self) -> std::string"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(scramble_packetize_sptr self, std::string name)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(scramble_packetize_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(scramble_packetize_sptr self) -> swig_int_ptr"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(scramble_packetize_sptr self) -> swig_int_ptr"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(scramble_packetize_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _scrambler_packets_same_seed_swig.scramble_packetize_sptr_message_subscribers(self, which_port)

scramble_packetize_sptr_swigregister = _scrambler_packets_same_seed_swig.scramble_packetize_sptr_swigregister
scramble_packetize_sptr_swigregister(scramble_packetize_sptr)


scramble_packetize_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
scramble_packetize = scramble_packetize.make;

class descramble_packetize(object):
    """
    <+description of block+>

    Constructor Specific Documentation:

    Return a shared_ptr to a new instance of scrambler_packets_same_seed::descramble_packetize.

    To avoid accidental use of raw pointers, scrambler_packets_same_seed::descramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::descramble_packetize::make is the public interface for creating new instances.

    Args:
        mask : 
        seed : 
        len : 
        frame_bit : 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def make(mask, seed, len, frame_bit):
        """
        make(int mask, int seed, int len, int frame_bit) -> descramble_packetize_sptr

        <+description of block+>

        Constructor Specific Documentation:

        Return a shared_ptr to a new instance of scrambler_packets_same_seed::descramble_packetize.

        To avoid accidental use of raw pointers, scrambler_packets_same_seed::descramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::descramble_packetize::make is the public interface for creating new instances.

        Args:
            mask : 
            seed : 
            len : 
            frame_bit : 
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_make(mask, seed, len, frame_bit)

    make = staticmethod(make)
    __swig_destroy__ = _scrambler_packets_same_seed_swig.delete_descramble_packetize
    __del__ = lambda self: None
descramble_packetize_swigregister = _scrambler_packets_same_seed_swig.descramble_packetize_swigregister
descramble_packetize_swigregister(descramble_packetize)

def descramble_packetize_make(mask, seed, len, frame_bit):
    """
    descramble_packetize_make(int mask, int seed, int len, int frame_bit) -> descramble_packetize_sptr

    <+description of block+>

    Constructor Specific Documentation:

    Return a shared_ptr to a new instance of scrambler_packets_same_seed::descramble_packetize.

    To avoid accidental use of raw pointers, scrambler_packets_same_seed::descramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::descramble_packetize::make is the public interface for creating new instances.

    Args:
        mask : 
        seed : 
        len : 
        frame_bit : 
    """
    return _scrambler_packets_same_seed_swig.descramble_packetize_make(mask, seed, len, frame_bit)

class descramble_packetize_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::scrambler_packets_same_seed::descramble_packetize)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(gr::scrambler_packets_same_seed::descramble_packetize)> self) -> descramble_packetize_sptr
        __init__(boost::shared_ptr<(gr::scrambler_packets_same_seed::descramble_packetize)> self, descramble_packetize p) -> descramble_packetize_sptr
        """
        this = _scrambler_packets_same_seed_swig.new_descramble_packetize_sptr(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __deref__(self):
        """__deref__(descramble_packetize_sptr self) -> descramble_packetize"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr___deref__(self)

    __swig_destroy__ = _scrambler_packets_same_seed_swig.delete_descramble_packetize_sptr
    __del__ = lambda self: None

    def make(self, mask, seed, len, frame_bit):
        """
        make(descramble_packetize_sptr self, int mask, int seed, int len, int frame_bit) -> descramble_packetize_sptr

        <+description of block+>

        Constructor Specific Documentation:

        Return a shared_ptr to a new instance of scrambler_packets_same_seed::descramble_packetize.

        To avoid accidental use of raw pointers, scrambler_packets_same_seed::descramble_packetize's constructor is in a private implementation class. scrambler_packets_same_seed::descramble_packetize::make is the public interface for creating new instances.

        Args:
            mask : 
            seed : 
            len : 
            frame_bit : 
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_make(self, mask, seed, len, frame_bit)


    def history(self):
        """history(descramble_packetize_sptr self) -> unsigned int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(descramble_packetize_sptr self, int which, int delay)
        declare_sample_delay(descramble_packetize_sptr self, unsigned int delay)
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(descramble_packetize_sptr self, int which) -> unsigned int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(descramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(descramble_packetize_sptr self) -> double"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_relative_rate(self)


    def start(self):
        """start(descramble_packetize_sptr self) -> bool"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_start(self)


    def stop(self):
        """stop(descramble_packetize_sptr self) -> bool"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(descramble_packetize_sptr self, unsigned int which_input) -> uint64_t"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(descramble_packetize_sptr self, unsigned int which_output) -> uint64_t"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(descramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(descramble_packetize_sptr self, int m)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(descramble_packetize_sptr self)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(descramble_packetize_sptr self) -> bool"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(descramble_packetize_sptr self, int m)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(descramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(descramble_packetize_sptr self, int i) -> long"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(descramble_packetize_sptr self, long max_output_buffer)
        set_max_output_buffer(descramble_packetize_sptr self, int port, long max_output_buffer)
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(descramble_packetize_sptr self, int i) -> long"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(descramble_packetize_sptr self, long min_output_buffer)
        set_min_output_buffer(descramble_packetize_sptr self, int port, long min_output_buffer)
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(descramble_packetize_sptr self, int which) -> float
        pc_input_buffers_full(descramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(descramble_packetize_sptr self, int which) -> float
        pc_input_buffers_full_avg(descramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(descramble_packetize_sptr self, int which) -> float
        pc_input_buffers_full_var(descramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(descramble_packetize_sptr self, int which) -> float
        pc_output_buffers_full(descramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(descramble_packetize_sptr self, int which) -> float
        pc_output_buffers_full_avg(descramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(descramble_packetize_sptr self, int which) -> float
        pc_output_buffers_full_var(descramble_packetize_sptr self) -> pmt_vector_float
        """
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(descramble_packetize_sptr self) -> float"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(descramble_packetize_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(descramble_packetize_sptr self)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(descramble_packetize_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(descramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(descramble_packetize_sptr self) -> int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(descramble_packetize_sptr self, int priority) -> int"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(descramble_packetize_sptr self) -> std::string"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_name(self)


    def symbol_name(self):
        """symbol_name(descramble_packetize_sptr self) -> std::string"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(descramble_packetize_sptr self) -> io_signature_sptr"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(descramble_packetize_sptr self) -> io_signature_sptr"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(descramble_packetize_sptr self) -> long"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(descramble_packetize_sptr self) -> basic_block_sptr"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(descramble_packetize_sptr self, int ninputs, int noutputs) -> bool"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(descramble_packetize_sptr self) -> std::string"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(descramble_packetize_sptr self, std::string name)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(descramble_packetize_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(descramble_packetize_sptr self) -> swig_int_ptr"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(descramble_packetize_sptr self) -> swig_int_ptr"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(descramble_packetize_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _scrambler_packets_same_seed_swig.descramble_packetize_sptr_message_subscribers(self, which_port)

descramble_packetize_sptr_swigregister = _scrambler_packets_same_seed_swig.descramble_packetize_sptr_swigregister
descramble_packetize_sptr_swigregister(descramble_packetize_sptr)


descramble_packetize_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
descramble_packetize = descramble_packetize.make;



